//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeDifference.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeZoneEntry
    {
        public int Id { get; set; }
        public string EntryName { get; set; }
        public string City { get; set; }
        public long Difference { get; set; }
        public int UserId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual User User { get; set; }
    }
}
